import { buildMockOpenAIResponse, buildOpenAIGenerationRequest, validateOpenAIGenerationRequest, validateOpenAIGenerationResponse } from "./openAIProviderContract.js";
import { createDirectServicePackage, validateDirectServicePackage } from "./directServiceLaneService.js";
import { createAffiliateCandidate, validateAffiliateCandidate } from "./affiliateLaneService.js";
import { createSNSCandidateSet, validateSNSCandidateSet } from "./snsMediaLaneService.js";

export const DIRECT_SERVICE_STORAGE_KEY="kevirio:direct-service-packages:v2";
export const AFFILIATE_STORAGE_KEY="kevirio:affiliate-candidates:v2";
export const SNS_STORAGE_KEY="kevirio:sns-candidate-sets:v2";
export const CROSS_LANE_STORAGE_KEY="kevirio:cross-lane-revenue:v2";
const CONFIG={
 [DIRECT_SERVICE_STORAGE_KEY]:["directServicePackagesById","servicePackageId",validateDirectServicePackage],
 [AFFILIATE_STORAGE_KEY]:["affiliateCandidatesById","affiliateCandidateId",validateAffiliateCandidate],
 [SNS_STORAGE_KEY]:["snsCandidateSetsById","snsCandidateSetId",validateSNSCandidateSet],
 [CROSS_LANE_STORAGE_KEY]:["orchestrationsById","orchestrationId",validateCrossLaneSummary],
};
function plain(v){return Boolean(v)&&typeof v==="object"&&!Array.isArray(v);}
function empty(key){return{schemaVersion:"2.0.0",dataMode:"mock",isMock:true,workspaceOnly:true,[CONFIG[key][0]]:{}};}
function load(storage,key){const raw=storage?.getItem?.(key);if(raw===null||raw===undefined)return{ok:true,workspace:empty(key)};try{const w=JSON.parse(raw);const [collection,,validator]=CONFIG[key];if(w.schemaVersion!=="2.0.0"||w.dataMode!=="mock"||w.isMock!==true||w.workspaceOnly!==true||!plain(w[collection]))throw new Error("workspace");for(const value of Object.values(w[collection]))if(!validator(value).valid)throw new Error("entity");return{ok:true,workspace:w};}catch{return{ok:false,status:"corrupted",errors:[{code:"CORRUPTED_STORAGE",field:key}]};}}
function write(storage,key,value){try{storage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
function hasForbiddenSourceField(value){if(Array.isArray(value))return value.some(hasForbiddenSourceField);if(!plain(value))return false;return Object.entries(value).some(([key,item])=>(key!=="actualRevenueConnected"&&/api.?key|credential|password|access.?token|refresh.?token|authorization|bearer|actual.?revenue|confirmed.?revenue|payment/i.test(key))||hasForbiddenSourceField(item));}
function validSource(s,context){return plain(s)&&!hasForbiddenSourceField(s)&&s.schemaVersion==="2.0.0"&&s.status==="publishReadyMock"&&s.dataMode==="mock"&&s.isMock===true&&Boolean(s.exportId)&&Boolean(s.correlationId)&&s.reviewDecisionId===context?.reviewDecision?.reviewDecisionId&&context?.reviewDecision?.decision==="approvedForMockWorkflow"&&(context?.latestRevision?.revisionCandidateId||null)===(s.sourceRevisionCandidateId||null)&&s.publishEnabled===false&&s.approvalConfirmed===false&&s.productionExecution===false&&s.externalExecution===false&&s.actualRevenueConnected===false&&s.ledgerAppend===false;}
function request(source,purpose,lane){const properties=Object.fromEntries(Object.keys(source).map(key=>[key,{}]));return buildOpenAIGenerationRequest({requestId:`openai-${purpose}-${source.exportId}`,purpose,correlationId:source.correlationId,sourceExportId:source.exportId,systemInstruction:"Generate a structured mock-only revenue candidate. Never claim actual results.",taskInstruction:`Create ${lane} candidate`,sourceContext:source,outputSchema:{lane,type:"object",properties,required:Object.keys(source),additionalProperties:false},privacyClassification:"internalMock",prohibitedData:["credentials","personalData","actualRevenue"],safetyRequirements:["mockOnly","noExternalExecution","noProductionExecution"],maxOutputTokens:2048,timeoutMs:15000,retryPolicy:{maxRetries:1,backoff:"bounded"}});}
export function validateCrossLaneSummary(v){const e=[];if(!v?.orchestrationId||!v?.lanes?.directService||!v?.lanes?.affiliate||!v?.lanes?.snsMedia)e.push({code:"LANES_REQUIRED"});if(v?.recommendedFirstLane!=="directService"||v?.liveProviderUsed!==false||v?.externalExecution!==false||v?.productionExecution!==false||v?.ledgerAppend!==false)e.push({code:"SUMMARY_CONTRACT_MISMATCH"});return{valid:!e.length,errors:e};}
export function orchestrateThreeRevenueLanes(storage,source,context={}){if(!validSource(source,context))return{ok:false,status:"source_invalid",message:"現在承認されているPublish-ready Mock成果物が必要です。",errors:[{code:"APPROVED_CURRENT_MOCK_EXPORT_REQUIRED"}]};const loaded={};for(const key of Object.keys(CONFIG)){loaded[key]=load(storage,key);if(!loaded[key].ok)return{ok:false,status:"corrupted",message:"保存済みWorkspaceを安全に確認できないため停止しました。",errors:loaded[key].errors};}
 const id=`three-lane-${source.exportId}`;const existing=loaded[CROSS_LANE_STORAGE_KEY].workspace.orchestrationsById[id];if(existing)return{ok:true,status:"existing",orchestration:existing,idempotent:true};
 const requests=[["directServiceDraft","directService"],["affiliateDraft","affiliate"],["snsDraft","snsMedia"]].map(([purpose,lane])=>request(source,purpose,lane));for(const req of requests){const rv=validateOpenAIGenerationRequest(req);const res=buildMockOpenAIResponse(req);if(!rv.valid||!validateOpenAIGenerationResponse(res).valid)return{ok:false,status:"provider_contract_invalid",message:"OpenAI Mock契約の検証に失敗しました。",errors:[...rv.errors,...(res.errors||[])]};}
 const direct=createDirectServicePackage(source),affiliate=createAffiliateCandidate(source),sns=createSNSCandidateSet(source);const validations=[validateDirectServicePackage(direct),validateAffiliateCandidate(affiliate),validateSNSCandidateSet(sns)];if(validations.some(v=>!v.valid))return{ok:false,status:"lane_invalid",message:"候補を保存せず停止しました。",errors:validations.flatMap(v=>v.errors)};
 const summary={orchestrationId:id,sourceExportId:source.exportId,correlationId:source.correlationId,schemaVersion:"2.0.0",dataMode:"mock",isMock:true,lanes:{directService:direct,affiliate,snsMedia:sns},recommendedFirstLane:"directService",recommendationReason:"Revenue First Rule: 最短で提案可能な制作サービスを先に確認します。",estimatedOwnerActions:["制作サービスの提案内容を確認する"],revenueReadiness:{directService:"proposalCandidateReady",snsMedia:"contentCandidateReady",affiliate:"programVerificationRequired"},status:"threeLaneCandidatesReady",liveProviderUsed:false,externalExecution:false,productionExecution:false,ledgerAppend:false,actualRevenueConnected:false};
 const entries=[[DIRECT_SERVICE_STORAGE_KEY,direct],[AFFILIATE_STORAGE_KEY,affiliate],[SNS_STORAGE_KEY,sns],[CROSS_LANE_STORAGE_KEY,summary]];for(const [key,entity]of entries){const [collection,idField]=CONFIG[key];if(Object.keys(loaded[key].workspace[collection]).length>=50)return{ok:false,status:"limit_exceeded",message:"Workspace上限のため保存しませんでした。",errors:[{code:"WORKSPACE_LIMIT_EXCEEDED",field:key}]};loaded[key].next={...loaded[key].workspace,[collection]:{...loaded[key].workspace[collection],[entity[idField]]:entity}};}
 const originals=entries.map(([key])=>[key,storage?.getItem?.(key)??null]);for(const [key]of entries){if(!write(storage,key,loaded[key].next)){let rollback=true;for(const [oldKey,raw]of originals)try{raw===null?storage.removeItem(oldKey):storage.setItem(oldKey,raw);}catch{rollback=false;}return{ok:false,status:rollback?"save_failed":"rollback_failed",message:"保存に失敗したため以前の状態へ戻しました。",errors:[{code:rollback?"TRANSACTION_ROLLED_BACK":"ROLLBACK_FAILED"}]};}}
 return{ok:true,status:"threeLaneCandidatesReady",orchestration:summary,idempotent:false};}
export function loadCrossLaneRevenue(storage,sourceExportId){const r=load(storage,CROSS_LANE_STORAGE_KEY);if(!r.ok)return r;const items=Object.values(r.workspace.orchestrationsById);return{ok:true,orchestration:sourceExportId?items.find(x=>x.sourceExportId===sourceExportId)||null:items.at(-1)||null};}
